language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shaswatsaxena/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shaswatsaxena/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-245423465613"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
