language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t shaswatsaxena/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shaswatsaxena/docker-react npm run test
